### ISSUE TITLE
Make it more obvious where you can click

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#279]
### _Why:_ Is your feature request related to a problem?
It is not obvious where you can click. There are a few hover effects, but it's really easy to miss them. One way of increasing the visibility could be to make more "discoverable" cursors, see examples in this issue.

### _What:_ Describe the solution you'd like
Change the cursor to a bigger version when hovering links to journal entries and rolls

### Additional context
These are suggestion cursors for displaying journal entry descriptions and for rolling dice:
![cursor-description](https://user-images.githubusercontent.com/4853677/178199162-8c860dfe-9e73-4a8a-bf30-c41aaac2a683.svg)
![cursor-roll](https://user-images.githubusercontent.com/4853677/178199154-df2984ba-642d-4a5a-865e-90053055cdce.svg)

To use them add css like this
```scss
  [data-journal-id] {
    cursor: url("./assets/images/ui/cursor-description.svg") 1 10, pointer;
    //cursor: url("./assets/images/ui/cursor-roll.svg") 1 10, pointer;
  }
```
